// eslint-disable-next-line react-refresh/only-export-components
export const IMAGES = {
  image1: new URL("./shakespeare.png", import.meta.url).href,
  mobile: new URL("./mobileShakespeare.png", import.meta.url).href,
  logo: new URL("./logo.svg", import.meta.url).href,
  profile: new URL("./profile.jpeg", import.meta.url).href,
  spot: new URL("./spot.svg", import.meta.url).href,
  hat: new URL("./hat.svg", import.meta.url).href,
  clubpetro: new URL("./clubpetro.svg", import.meta.url).href,
  skolen: new URL("./skolen.svg", import.meta.url).href,
  calendar: new URL("./calendar.svg", import.meta.url).href,
  downArrow: new URL("./downArrow.svg", import.meta.url).href,
  cpDashboard: new URL("./cpdashboard.png", import.meta.url).href,
  materialUi: new URL("./mui-logo.svg", import.meta.url).href,
  react: new URL("./react-logo.svg", import.meta.url).href,
  ts: new URL("./ts-logo.svg", import.meta.url).href,
  footerLogo: new URL("./footerLogo.svg", import.meta.url).href,
  left: new URL("./left.svg", import.meta.url).href,
  right: new URL("./right.svg", import.meta.url).href,
  design: new URL("./design.svg", import.meta.url).href,
  experience: new URL("./experience.svg", import.meta.url).href,
  code: new URL("./code.svg", import.meta.url).href,
  darkIcon: new URL("./dark-icon.svg", import.meta.url).href,
  lightIcon: new URL("./light-icon.svg", import.meta.url).href,
  wine: new URL("./wine.svg", import.meta.url).href,
  cpscreens: new URL("./mainProjects/cpscreens.png", import.meta.url).href,
  fincheck: new URL("./mainProjects/fincheck.png", import.meta.url).href,
  otts: new URL("./mainProjects/otts.png", import.meta.url).href,
  skolenScreens: new URL("./mainProjects/skolen.png", import.meta.url).href,
  spiderMan: new URL("./repositories/spiderman.png", import.meta.url).href,
  places: new URL("./repositories/places.png", import.meta.url).href,
};
